app/Http/routes.php
<?php

/*
handles user authentications 
sign up, login, reset password
*/

Route::get('auth/register', 'Auth\UsersController@getRegister');
Route::post('auth/register', 'Auth\UsersController@postRegister');

Route::get('auth/login', 'Auth\UsersController@getLogin');
Route::post('auth/login', 'Auth\UsersController@authenticate');
Route::get('auth/logout', 'Auth\UsersController@logout');

/*
handles methods like;
index,create, edit, show, store, update, destroy..  
*/

Route::group(['prefix' => 'files','middleware'=>'auth'], function(){

        Route::get('/', ['as'=>'files.index','uses'=>'FilesController@index', 'permission' => 'view_all_files']);
        
        Route::post('/', ['as'=>'files.create','uses'=>'FilesController@store', 'permission' => 'add_file']);

        Route::get('/create', ['as'=>'files.create','uses'=>'FilesController@create', 'permission' => 'add_file']);
		/*
		route to view director's requests
		*/
		Route::get('dir_request',['uses'=>'FilesController@dir_request','as'=>'files.dir_request.index', 'permission' => 'view_requests']);

        Route::get('/{id}', ['as'=>'files.update','uses'=>'FilesController@edit', 'permission' => 'edit_file']);

        Route::patch('/{id}', ['as'=>'files.edit','uses'=>'FilesController@update', 'permission' => 'edit_file']);



        Route::delete('/{id}', ['as'=>'files.destroy','uses'=>'FilesController@destroy', 'permission' => 'delete_file']);
        
    });

/*
 named route to create and store file requests sent to directors
*/

Route::post('files/filerequest',['uses'=>'FilesController@storefilerequest', 'as' =>'files.request.store', 'permission' =>  'request_action']);

Route::get('files/filerequest/{id}',['uses'=>'FilesController@filerequest', 'as' =>'files.filerequest.create', 'permission' =>  'request_action']);



/*
route to view all files of a authenticated director
*/

Route::get('files/dir_files',['uses'=>'FilesController@dir_files','as'=>'files.dir_files.index']);
/*
route to view all documents of a authenticated director
*/
Route::get('files/dir_documents',['uses'=>'FilesController@dir_documents','as'=>'files.dir_documents.index', 'permission' => 'view_particular_documents']);



/*
route to close a file display date.
*/

Route::delete('files/close_file/{file_id}',['uses'=>'FilesController@close_file','as'=>'files.close_file.index', 'permission' => 'close_file']);


/*
route to view document creation form
*/

Route::get('files/doc_create/{file_id}', ['uses'=>'FilesController@doc_create', 'as'=>'files.doc_create.create', 'permission'=> 'add_document']);
/*
route to store document info
*/
Route::post('files/doc_create',['uses'=>'FilesController@storedoc_create', 'as' =>'files.request.store', 'permission'=> 'add_document']);

// show list of documents

Route::get('files/documents/{file_id}',['uses'=>'FilesController@documents','as'=>'files.documents.index', 'permission' => 'view_particular_documents']);

// edit document

Route::get('files/documents/{id}/doc_edit', ['uses'=>'FilesController@doc_edit','as'=>'files.documents.doc_edit', 'permission'=> 'edit_document']);

Route::post('files/documents{id}', ['uses'=>'FilesController@doc_update','as'=>'files.documents.doc_update', 'permission'=> 'edit_document']);

// request for action
Route::get('files/doc_request/{id}',['uses'=>'FilesController@doc_request', 'as' =>'files.doc_request.create', 'permission' => 'request_action']);

Route::post('files/doc_request',['uses'=>'FilesController@storedoc_request', 'as' =>'files.doc_request.store', 'permission' => 'request_action']);

//close a document
Route::get('files/close_document/{id}',['uses'=>'FilesController@close_document','as'=>'files.close_document.index', 'permission' => 'close_document']);

// delete a document
Route::delete('files/documents/{id}', ['uses'=>'FilesController@doc_destroy', 'as'=>'documents.doc_destroy', 'permission' => 'delete_document']);

 // check if action is done
Route::delete('files/check_action/{id}',['uses'=>'FilesController@check_action','as'=>'files.check_action']);

//send notification
Route::get('emails/send_notification', ['uses'=>'FilesController@send_notification', 'as'=>'emails.send_notification']);


//  handles user roles
Route::resource('role','RoleController');

// add permissions
Route::get('role/permissions/{role_id}', ['uses'=>'RoleController@permissions', 'as'=>'role.permissions']);

Route::post('role/permissions/{role_id}', ['uses'=>'RoleController@store_permissions', 'as'=>'role.permissions.store']);

//assign role
Route::get('users',['uses'=>'RoleController@users','as'=>'role.users']);

Route::get('role/assign_role/{user_id}', ['uses'=>'RoleController@assign_role', 'as'=>'role.assign_role']);

Route::post('role/assign_role/{user_id}', ['uses'=>'RoleController@storeassign_role', 'as'=>'role.assign_role.store']);

// route to view logs
Route::get('logs',['uses'=>'RoleController@logs','as'=>'role.logs']);

// route to view reports
Route::get('reports',['uses'=>'RoleController@reports','as'=>'role.reorts']);

app/Role.php
<?php
 namespace App;

use Zizaco\Entrust\EntrustRole;

class Role extends EntrustRole
{
	protected $fillable =[
		'name',
		'display_name',
		'description'
	];
}

app/Http/Controllers/RoleController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;

use App\Http\Requests;
use App\Role;
use App\Permission;
use App\RolePermission;
use App\RoleUser;
use App\User;
use App\Log;
use App\Report;
use App\Document_action;
use App\Http\Controllers\Controller;

class RoleController extends Controller
{
    /**
     * Display a listing of roles
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
       $roles = Role::All();

      return view('role.role',compact('roles'));
    }

    /**
     * Show the form for creating a new role
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
         return view ('role/create_role');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
         $role= new Role ($request->all());

        $role->save();
        return redirect('role'); 
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $role = Role::findOrFail($id); 

        return view('role.edit_role',compact('role'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $role= Role::findOrfail($id);

         $role->update($request->all());

        return redirect('role');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
         $role = Role::find($id);

        $role->delete();

        return redirect('role');
    }

    public function permissions($role_id)
    {
         $role = Role::find($role_id);
          $role->perms;
          $permissions = Permission::All();

        return view('role.permissions',compact('permissions','role'));
    }

    public function store_permissions(Request $request, $role_id)
    {
        $role = Role::findOrFail($role_id);

        $role->perms()->sync($request->permission);

        return redirect('role');

    }

    // get all users from the database
    public function users()
    {
        $users = User::All();
      return view('role.users',compact('users'));  
    }

    //assign roles to users
    public function assign_role($user_id)
    {
          $user = User::findOrFail($user_id);
          $user->roles;
          $roles = Role::All();

        return view('role.assign_role',compact('roles', 'user'));
    }

    public function storeassign_role(Request $request, $user_id)
    {
        $user = User::findOrFail($user_id);

        $user->roles()->sync($request->role);

        return redirect('role');

    }

    //get all logs
    public function logs()
    {
        $logs = Log::All();
        return view('role.logs',compact('logs'));
    }

    //get reports
    public function reports()
    {
       
        $reports = Document_action::getCategory();

       
        return  view('role.reports', compact('reports'));
    }
               
}

resources/views/role/assign_role.blade.php
@extends('dashboard_app')

@section('content')
	<form action="{{route('role.assign_role',$user->id)}}" method="post">
	<input type="hidden" name="_token" value="{{ csrf_token() }}">

	 <div class="card-box table-responsive">
	 	<table>	
			<tbody>
		        @foreach($roles as $role)
					<tr>
			            <td>

			            <input type="checkbox" name="role[]" value="{{$role->id}}" 	{{($user->roles->contains('id',$role->id))?'checked="checked"':""}} 			            
			            />
							<!-- (condition)?statement1:statement2 ....ternary statement-->
			            
			            </td>
			            <td>{{$role->display_name}}</td>
			        </tr>
		        @endforeach
			      <!-- end foreach -->
			</tbody>
			</table>
    	</div>
    	
	    	 <button type="submit" class="btn btn-primary" id="btn-login" class="btn btn-primary form-control">Save</button>
    	 </form>
@stop

resources/views/role/assign_role_backup.blade.php
 @extends('new_layout')
@section('content')
	<div id="viewfiles-wrap">
	<form action="{{route('role.assign_role',$user->id)}}" method="post">
	<input type="hidden" name="_token" value="{{ csrf_token() }}">

	 <div class="card-box table-responsive">
	 	<table>	
			<tbody>
		        @foreach($roles as $role)
					<tr>
			            <td>

			            <input type="checkbox" name="role[]" value="{{$role->id}}" 	{{($user->roles->contains('id',$role->id))?'checked="checked"':""}} 			            
			            />
							<!-- (condition)?statement1:statement2 ....ternary statement-->
			            
			            </td>
			            <td>{{$role->display_name}}</td>
			        </tr>
		        @endforeach
			      <!-- end foreach -->
			</tbody>
			</table>
    	</div>
    	
	    	 <button type="submit" class="btn btn-deep-green" id="btn-login" class="btn btn-primary form-control">Save</button>
    	 </form>
    </div>
@stop

resources/views/role/create_role.blade.php
@extends('dashboard_app')

@section('content')
	 {!!Form::open(['url'=>route('role.store')]) !!}
	
	@include('role.role_form',['submitButtonText'=>'Create'])
	 
	 {!!Form::close() !!}

     @include('errors.list')
@stop

resources/views/role/create_role_backup.blade.php
@extends('new_layout')

@section('content')
	 {!!Form::open(['url'=>route('role.store')]) !!}
	
	@include('role.role_form',['submitButtonText'=>'Create'])
	 
	 {!!Form::close() !!}

     @include('errors.list')
@stop

resources/views/role/edit_role.blade.php
@extends('dashboard_app')

@section('content')
	 {!!Form::model($role, array('route' => array('role.update', $role->id),'method'=>'PATCH')) !!}
	
	@include('role.role_form',['submitButtonText'=>'Save'])
	 
	 {!!Form::close() !!}

		@include('errors.list')

@stop

resources/views/role/edit_role_backup.blade.php
@extends('new_layout')

@section('content')
	 {!!Form::model($role, array('route' => array('role.update', $role->id),'method'=>'PATCH')) !!}
	
	@include('role.role_form',['submitButtonText'=>'Save'])
	 
	 {!!Form::close() !!}

		@include('errors.list')

@stop

resources/views/role/logs.blade.php
@extends('dashboard_app')

@section('content')
	<h3><i class="fa fa-sliders" aria-hidden="true"></i> Logs</h3>
	<hr>
	<div class="x-panel">
		<div id="viewfiles-wrap">
			<div class="x-content">
				<div class="row">
					<div class="col-sm-12">
						<div class="card-box table-responsive">	
							<table id="table1" class="table table-striped table-bordered">
							<thead>
								<th>No.</th>
								<th>User Id</th>
								<th>Model</th>
								<th>Action</th>
								<th>Content</th>
							</thead>
							<tbody>
							@foreach($logs as $log)
								<tr>
									<td>{{$log->id}}</td>
									<td>{{$log->user_id}}</td>
									<td>{{$log->model}}</td>
									<td>{{$log->action}}</td>
									<td>{{$log->content}}</td>
								</tr>
							@endforeach
							</tbody>
							</table>
						</div>
					</div>
				</div>
			</div>
		</div>
	</div>
@stop

resources/views/role/permissions.blade.php
@extends('dashboard_app')

@section('content')
	<h3><i class="fa fa-key" aria-hidden="true"></i> Permissions</h3>
		<hr>
	<form action="{{url('role/permissions', $role->id)}}" method="post">
	<input type="hidden" name="_token" value="{{ csrf_token() }}">

	 <div class="card-box table-responsive">
	 	<table>	
			<tbody>
		        @foreach($permissions as $permission)
					<tr>
			            <td>

			            <input type="checkbox" name="permission[]" value="{{$permission->id}}" 	{{($role->perms->contains('id',$permission->id))?'checked="checked"':""}} 
			            
			            />
							<!-- (condition)?statement1:statement2 ....ternary statement-->
			            
			            </td>
			            <td>{{$permission->display_name}}</td>
			        </tr>
		        @endforeach
			      <!-- end foreach -->
			</tbody>
			</table>
    	</div>
    	
	    	 <button type="submit" class="btn btn-primary" id="btn-login" class="btn btn-primary form-control">Save</button>
    	 </form>
@stop

resources/views/role/permissions_backup.blade.php
 @extends('new_layout')
@section('content')
	<div id="viewfiles-wrap">
	<form action="{{url('role/permissions', $role->id)}}" method="post">
	<input type="hidden" name="_token" value="{{ csrf_token() }}">

	 <div class="card-box table-responsive">
	 	<table>	
			<tbody>
		        @foreach($permissions as $permission)
					<tr>
			            <td>

			            <input type="checkbox" name="permission[]" value="{{$permission->id}}" 	{{($role->perms->contains('id',$permission->id))?'checked="checked"':""}} 
			            
			            />
							<!-- (condition)?statement1:statement2 ....ternary statement-->
			            
			            </td>
			            <td>{{$permission->display_name}}</td>
			        </tr>
		        @endforeach
			      <!-- end foreach -->
			</tbody>
			</table>
    	</div>
    	
	    	 <button type="submit" class="btn btn-deep-green" id="btn-login" class="btn btn-primary form-control">Save</button>
    	 </form>
    </div>
@stop

resources/views/role/reports.blade.php
@extends('dashboard_app')

@section('content')
	<h3><i class="fa fa-bar-chart-o" aria-hidden="true"></i> General Report</h3>
	<hr />
	<div class="card-box table-responsive">	
		<table id="table1" class="table table-striped table-bordered">
			<thead>
				<th>Name</th>
				<th>Type of Document</th>
				<th>Number of Documents attended per week</th>
				<th>Total</th>
			</thead>
			<tbody>
				@foreach($reports as $report)
				<tr>
					<td>{{$report->fname}} {{$report->mname}} {{$report->lname}}</td>
					<td>{{$report->category}}</td>
					<td>{{$report->total}}</td>
					<td> </td>
				</tr>

				@endforeach
			</tbody>
		</table>
	</div> <!-- end card-box table-responsive -->




@stop

resources/views/role/role_backup.blade.php
@extends('new_layout')

@section('content')

	<div id="viewfiles-wrap">
		<h3><i class="fa fa-user" aria-hidden="true"></i> Roles</h3>
		<hr>
		<a class="btn btn-default"  href="{{url('users')}}"><i class="fa fa-user"></i> Users</a>
		<a class="btn btn-default"  href="{{url('logs')}}"><i class="fa fa-sliders"></i> Logs</a>
		<div class="x_content">
			
                    <div class="card-box table-responsive">
						<table  id="table1" class="table table-hover table-bordered">	
						<thead class="thead">
							<th>No.</th>
								<th>Name</th>
								<th>Display Name</th>
								<th>Description</th>
								<th>Action</th>
						</thead>
						<tbody>
						@foreach($roles as $role)
							<tr>
								<td>{{$role->id}}</td>

								<td>{{$role->name}}</td>

								<td>{{$role->display_name}}</td>
								<td>{{$role->description}}</td>
								<td>
					                <a class="btn btn-sm btn-default" href="{{route('role.permissions', $role->id)}}"><i class="fa fa-cogs"></i>
					                </a>
					                <a class="btn btn-sm btn-default" href="{{route('role.edit',$role->id)}}"><i class="fa fa-pencil"></i>
					                </a>
					                <a class="btn btn-sm btn-default" data-method="delete" data-token="{{csrf_token()}}" data-confirm="Are you sure?" href="{{route('role.destroy', $role->id)}}"><i class="fa fa-trash"></i>
					                </a>
					            </td>
							</tr>
									
												
						@endforeach
						</tbody>

						</table>
					</div> <!-- end of card-box table-responsive --> 
			
		</div> <!-- end of x_content --> 
	</div> <!-- end of viewfiles-wrap -->

@stop

resources/views/role/role_form_backup.blade.php
<!-- Form without header-->
<div id="doc_info">
    <div class="row">
    <div class="col-md-offset-2 col-md-8 col-md-offset-2">
        <div class="card">
            <div class="card-block">

                <!--Header-->
                <div class="text-xs-center">
                    <h3><i class="fa fa-pencil"></i> User Role:</h3>
                    <hr class="m-t-2 m-b-2">
                </div>

                <!--Body-->
                <br>

                <!--Body-->
                  <div class="form-group">
        
                        {!!Form::label('name','Name') !!}
                        {!!Form::text('name',null, ['class'=> 'form-control'])!!}
                        
                     </div>

                <div class="form-group">
                        
                        {!!Form::label('display_name','Display Name') !!}
                        {!!Form::text('display_name',null, ['class'=> 'form-control'])!!}
                        
                     </div>

                <div class="form-group">
                        
                        {!!Form::label('description','Description') !!}
                        {!!Form::text('description',null, ['class'=> 'form-control'])!!}
                        
                     </div>
                <!-- <div class="text-xs-center">
                    <button type="submit" id="btn-form" class="btn btn-deep-blue">Submit</button>
                </div> -->
                <div class="form-group">
                    <!-- <div class="submit-btn"> -->
                        {!!Form::submit($submitButtonText,['id'=>'submit-btn','class'=> 'btn btn-primary form-control'])!!}
                    <!-- </div> -->
                </div>

            </div>
        </div>
    </div>
</div>
</div>
<!--/Form without header

resources/views/role/users.blade.php
@extends('dashboard_app')

@section('content')
	<h3><i class="fa fa-users" aria-hidden="true"></i> Users</h3>
	<hr />
	<div class="card-box table-responsive">	
		<table id="table1" class="table table-striped table-bordered">
			<thead>
				<th>No.</th>
				<th>First Name</th>
				<th>Middle Name</th>
				<th>Last Name</th>
				<th>Position</th>
				<th>Abbreviation</th>
				<th>Mobile number</th>
				<th>Email</th>
				<th>Action</th>
			</thead>
			<tbody>
			@foreach($users as $user)
				<tr>
					<td>{{$user->id}}</td>
					<td>{{$user->fname}}</td>
					<td>{{$user->mname}}</td>
					<td>{{$user->lname}}</td>
					<td>{{$user->position}}</td>
					<td>{{$user->abbreviation}}</td>
					<td>{{$user->mobile_no}}</td>
					<td>{{$user->email}}</td>
					<td>
						<a class="btn btn-sm btn-primary" href="{{route('role.assign_role', $user->id)}}"><i class="fa fa-key"></i>
		            </a>
					</td>
				</tr>
			@endforeach
			</tbody>
		</table>
	</div> <!-- end card-box table-responsive -->
@stop

resources/views/role/users_backup.blade.php
@extends('new_layout')

@section('content')
	<div class="x-panel">
		<div id="viewfiles-wrap">
			<div class="x-content">
				<div class="row">
					<div class="col-sm-12">
						<div class="card-box table-responsive">	
							<table id="table1" class="table table-striped table-bordered">
							<thead>
								<th>No.</th>
								<th>First Name</th>
								<th>Middle Name</th>
								<th>Last Name</th>
								<th>Position</th>
								<th>Abbreviation</th>
								<th>Mobile number</th>
								<th>Email</th>
								<th>Action</th>
							</thead>
							<tbody>
							@foreach($users as $user)
								<tr>
									<td>{{$user->id}}</td>
									<td>{{$user->fname}}</td>
									<td>{{$user->mname}}</td>
									<td>{{$user->lname}}</td>
									<td>{{$user->position}}</td>
									<td>{{$user->abbreviation}}</td>
									<td>{{$user->mobile_no}}</td>
									<td>{{$user->email}}</td>
									<td>
										<a class="btn btn-sm btn-default" href="{{route('role.assign_role', $user->id)}}"><i class="fa fa-cogs"></i>
					                </a>
									</td>
								</tr>
							@endforeach
							</tbody>
							</table>
						</div>
					</div>
				</div>
			</div>
		</div>
	</div>

@stop